[config]
textures = { root = "sprites/" }
sounds = { root = "sounds/" }
shaders = { root = "shaders/" }

[textures]

# Backgrounds
computer_room = "room/room.png"
first_puzzle_room = "room/first_puzzle_room.png"
first_puzzle_room_wall_overlay = "room/first_puzzle_room_wall_overlay.png"

walkway_room = "room/walkway_room/walkway_room.png"
walkway_railing = "room/walkway_room/walkway_railing.png"
walkway_walls = "room/walkway_room/walkway_walls.png"

status_room = "room/status_room/status_room.png"

food_room = "room/food_room/food_room.png"
food_room_taken_can = "room/food_room/food_room_taken_can.png"

upper_hall_background = "room/upper_hall/upper_hall_background.png"
upper_hall_walls = "room/upper_hall/upper_hall_walls.png"

upper_door_background = "room/upper_door/upper_door_background.png"
upper_door_walls = "room/upper_door/upper_door_walls.png"

table = "room/table/table.png"
button = "room/button/button.png"
passage = "room/passage/passage.png"

first_puzzle_room_table = "room/first_puzzle_room_table.png"
table_lamp = "room/table_lamp.png"
note = "room/note/note.png"
table_note = "room/table_note.png"

dial = "room/dial/dial.png"
dial_handle = "room/dial/dial_handle.png"
dial_full = "room/dial/dial_full.png"

look_up_bg = "room/walkway_room/look_up_bg.png"
look_up_fan = "room/walkway_room/look_up_fan.png"
look_down = "room/walkway_room/look_down.png"

status_room_computer = "room/status_room/computer_screen.png"

upper_door_look_outside = "room/upper_door/look_outside.png"

mainchar = "mainchar/mainchar.png"
food_room_look_at_can = "room/food_room/food_room_look_at_can.png"

# Cave tilemap
cave_tilemap = "room/cave_tileset/cave_tileset.png"

[sounds]
button_press = "button_press.ogg"

footstep = "footstep.ogg"
footstep_metal = "footstep_metal.ogg"

rotation_click = "rotation_click.ogg"

puzzle_jingle = "puzzle_jingle/puzzle_jingle.ogg"
dial_jingle = "dial_jingle/dial_jingle.ogg"

wind = "wind.ogg"
water = "water.ogg"
radio = "radio.ogg"

[shaders.room_darker]
file = "room_darker.frag"
args = { n = "integer", ambientLightLevel = "float" }

[shaders.circle_light]
file = "circle_light.frag"
args = { n = "integer", brightness = "float", point = "vec2i" }
need_screen_size = true

[shaders.cave]
file = "cave.frag"
args = { n = "integer", lightPoint = "vec2i", entrancePoint = "vec2i" }
need_screen_size = true