[assets.sprites]
computer_room = "resources/sprites/room/room.png"
table = "resources/sprites/room/table/table.png"
button = "resources/sprites/room/button/button.png"

[assets.sounds]
button_press = "resources/sounds/button_press.ogg"

# Background

[entities.background.drawable_sprite]
sprite_asset = "computer_room"
z = 0

[entities.table.drawable_sprite]
sprite_asset = "table"
z = 1
position = [97, 706]

[entities.table.interaction]
initial_state = "disabled"
callback_name = "computer_switch_to_terminal"

# Button

[entities.button.drawable_sprite]
sprite_asset = "button"
z = 1
position = [1020, 672]

[entities.button.animation]
sheet = "resources/sprites/room/button/"
playing = false
playable = false

[entities.button.interaction]
initial_state = "disabled"
state_map = { disabled = 1, enabled = 2 }
callback_name = "activate_computer"
interaction_sound_asset = "button_press"

# Player

[entities.player]
prefab = "player"

[entities.player.drawable_sprite]
position = [420, 820]