[assets.sprites]
computer_room = "resources/sprites/room/room.png"
table = "resources/sprites/room/table/table.png"
button = "resources/sprites/room/button/button.png"

[assets.sounds]
button_press = "resources/sounds/button_press.ogg"

# Background

[entities.background.drawable_sprite]
sprite_asset = "computer_room"
z = 0

[entities.table.drawable_sprite]
sprite_asset = "table"
z = 1

[entities.table.transformable]
position = [97, 706]

[entities.table.interaction]
initial_state = "disabled"
callback_name = "computer_switch_to_terminal"

[entities.table.collider]
mode = "sprite"
trigger = true

# Button

[entities.button.drawable_sprite]
sprite_asset = "button"
z = 1

[entities.button.transformable]
position = [1020, 672]

[entities.button.animation]
sheet = "resources/sprites/room/button/"
playing = false
playable = false

[entities.button.interaction]
initial_state = "disabled"
state_map = { disabled = 1, enabled = 2 }
callback_name = "activate_computer"
interaction_sound_asset = "button_press"

[entities.button.collider]
mode = "sprite"
trigger = true

# Player

[entities.player]
prefab = "player"

[entities.player.transformable]
position = [420, 820]

[entities.left_wall]
transformable = { position = [350, 500] }
collider = { mode = "constant", size = [10, 400] }

[entities.right_wall]
transformable = { position = [1130, 500] }
collider = { mode = "constant", size = [10, 400] }
