[prefab]
name = "computer_room"
removed_entities = [ "button" ]

[entities.table.interaction]
activatable_callback_name = "first_puzzle_solved"
callback_name = "computer_switch_to_terminal"

# Passage

[entities.passage]
prefab = "passage"
transformable = { position = [1000, 750] }
interaction = { args = [ "first_puzzle_room" ] }