[hunger_iteration]
text = """
That last iteration wasn't a good idea at all. They turned violent on each other fighting for resources.. Really, all these things I come up
with aren't working out well. Maybe it's good the way it is already. I'll leave some things that shouldn't hurt anyone in, but
the rest is going into the trash."""
bottom_text = """
passwd: aqualung

ctrl z switch instance
"""