[hunger_iteration]
text = """
That last iteration wasn't a good idea at all. Really, most things I came up with don't work that well, this time they turned violent against other
creatures. Eventually, when they eradicated those, they started killing each other.. Except her, of course. Should've seen that coming. This
one's going into the trash too."""
bottom_text = """
passwd: aqualung

ctrl z switch instance
"""