[hunger_iteration]
text = """
That last iteration wasn't a good idea at all. It seems like most of the features implemented don't work that well for the world, this time they \
turned violent against other creatures. Eventually, when they eradicated those, they started killing each other.. Except her, of course. \
I should've seen that coming. This one's going to the archive too."""
bottom_text = """
passwd: aqualung

ctrl z switch instance
"""