[shaders.room_darker]
n = 1
ambientLightLevel = 0.4

[shaders.circle_light]
n = 2
point = [237, 740]
brightness = 0.1

# Background

[entities.background.drawable]
kind = "sprite"
texture_asset = "computer_room"
z = 0

[entities.table.drawable]
kind = "sprite"
texture_asset = "table"
z = 1

[entities.table.transformable]
position = [97, 706]

[entities.table.interaction]
initial_state = "disabled"
activatable_callback = { module = "components.interaction", name = "first_button_pressed" }
callback = { module = "components.interaction", name = "computer_switch_to_terminal" }
action_text = "use the computer"

[entities.table.collider]
mode = "sprite"
trigger = true

# Button

[entities.button.drawable]
kind = "sprite"
texture_asset = "button"
z = 1

[entities.button.transformable]
position = [1020, 672]

[entities.button.animation]
sheet = "resources/sprites/room/button/"
playing = false
playable = false

[entities.button.interaction]
initial_state = "disabled"
state_map = { disabled = 1, enabled = 2 }
activatable_callback = { module = "components.interaction", name = "state_equal", args = ["disabled"] }
callback = { module = "components.interaction", name = "activate_computer" }
interaction_sound_asset = "button_press"
action_text = "press the button"

[entities.button.collider]
mode = "sprite"
trigger = true

# Player

[entities.player]
prefab = "player"

[entities.player.transformable]
position = [420, 820]

# Walls

[entities.left_wall]
transformable = { position = [350, 500] }
collider = { mode = "constant", size = [10, 400] }

[entities.right_wall]
transformable = { position = [1130, 500] }
collider = { mode = "constant", size = [10, 400] }

[entities.interaction_text]
prefab = "interaction_text"