* Prologue
  Hello? Can you hear me?

  Who are you? And who am I?

  I'm <narrator>, who you are I do not know, you just appeared here. Can you at least remember your name?

  No, i don't think i can actually.

  How should i call you then?

  I guess <P> would do for for now.

  Very well, <P>. Since you're here, i'll show you around.

  You are standing in an empty room with the <narrator>.

  Well, there isn't much much to show now. There was more, but it's got cut off. Maybe you could do something about that?

  And just how would i do that?

  You're sitting in front of a computer screen, aren't you?

  <The background becomes a screen frame instead of just white>

  Well, now that you mention it. Yeah, i do..

  Maybe check your surroundings out? I'll still be here, of course. Not like i can go anywhere :)

* First time in the room
  There's a room where the player is in. The player is some ambigous figure in a hoodie.

  The room around the player is badly lit, there's a lever on the wall on the right, while the wall on the left is the wall where
  the computer is.  When the player presses the lever, a sound is heard from the computer. The player then goes back to the computer.

* At the computer after the room
  You're no longer standing in the room, now around you is a midnight forest. You ask <narrator>, who is still
  standing near, what is happening.

  Well, you did something, and now there's a forest. That is what i was talking about when i told you
  that there was more. This forest is a fraction of it. This is where we all woke up.

  What do you mean "we all"? There are more people here?

  There were. I don't know if they're still here. It's been some time since there was anything here.
  But now you're here at least. And the forest is back too.

  Then what do you mean by "woke up"?

  We all found ourselves here just like you did, with no memory of what happened or who we were.
  When i found myself here, there was nobody else around. It was pretty lonely, the only thing
  i would do is walk through the forest, looking around for anything to do at all. With time though,
  more people came, just like me, with no recollection of what happened. They found themselves in this
  very forest. They went looking for something to do, like i did, and eventually met the others.
  There were all kinds of creatures appearing, too. Some of them were very much sentient, like me and you,
  some were more animal-like, just following instincts. What seemed to connect them was that they all were just as confused.

  So what happened? Where did everyone go?

  Something bad. I'm not sure what exactly happened, but it seemed like the world was being cut off piece by piece.
  One day, someone found a wall at the edge of the forest. A wall that looked just like those
  in the room we were just in. Just a gray wall that seemed to extend in all directions. The next day the wall grew closer.
  People were scaried. Long story short, eventually the whole world shrank to a single room. I don't know were the other people went,
  i haven't seen them in a while. I have no idea how much time i've been in that gray box, alone. But now you're here,
  and that probably means something is happening. Now, let's at least go for a walk, shall we? I've been on this same spot for so long it
  feels like forever. I'd like to at least take a stroll through the forest while we can.

  Sure, there's no point in staying here anyway.

  <You walk through the forest you were now in. It's not very thick, but there is still plenty of plants and trees. Although all of them
  look somewhat similiar with small variation>

  <P>: So.. what was life like here, anyway? Until everything diasppeared, that is..

  Oh you know, pretty peaceful i guess. It's not like we had any specific needs to have fights for. I'd say just your usual life, but i can't really
  judge fairly what usual life is like, because i've only ever known my own life here...

  True... I'd still want to know what it was like here.

  Well, after some time spent just going around the forest and finding other people, we decided to settle down somewhere. This is where we're currently heading,
  or so i hope, since i haven't seen this forest in so long. For some reason, there were some people that knew how to make "instruments", while others didn't. They couldn't
  explain where they got this knowledge, it's like it just appread in their heads when the need arose. These people would make these simple instruments from what was in the forest. It looked
  like they were just smashing things together and then the tools just appeared in their hands. Others tried to do this too, but would not succeed. Then the instruments
  were used to chop down the trees, uproot stumps, and build from that. Other people knew how to make dyes from flowers and other plants. They did it the same way others made tools
  The first houses were pretty simple, but of course, as time went on people would make them more sophisticated and fancy, to stand out more. Eventually we learned how to make other things, too.
  Some people, who were not able to create anything by hand, would create for other's joy and entertainment, so they used paints and dyes to draw pictures, others would use paper and black dyes
  to write tales and stories. Some volunteered to document the history of what was happening around them, and with those people the libraries appeared. They'd organize their
  written history in books and store them all in one place. Sounds pretty cool, right?

  Yeah, that's useful, probably?

  Maybe for the new people that come like you it would be. People here wouldn't age, they were all around for as long as i can remember, until what happened happened.
  Anway, after sometime fire was discovered and the first library burnt down with most of the books in it. Some were rewritten from memory after that, but many still
  went away forever.

  Oh.

  Indeed. So the next library was built out of stone. Not long after that concrete was discovered by accident. Same happened with glass.
  Fast forward some time, and there were now not only one place where everyone lived, a city was built, and it was big, with
  asphalt roads and tall buildings. People would come up with different work for themselves to spend time. Now they were trying to understand the world even more throughly.
  Trying to find out how things work. Eventually, a person showed up. They didn't name themselves, but claimed to be the creator
  of this world. They moved rather unnaturally, as if controlled by strings by a puppetmaster, and not a good one at that. They told the researchers about the world,
  about how that person watched them grow and that now they had come to them in person. A bit after that, the "creator" disappeared, and then the thing happened, the world was vanishing.
  Panic. And then everything ceased to be. Except me. I was still there, for some reason.

  That is one crazy story, but of course i have no choice except to belive it. I have no idea what i am doing here anyway, so might as well take some
  explanation for granted, you really now a lot more about things than I do. Oh and by the way, you so confidently asked me if i'm sitting in front of a computer screen,
  how come you were so certain?

  There's something in the way you move that gives it up, similiar to how the creator was. It might just be my imagination, i really wanted to belive that you had something in common
  with them, and it turned out you did. Anyway, we're there. This is the place where i used to live.

  <You see something reminiscent of a village. There are a lot of cottages of all shapes and colors. No living creature seems
  to be around except two of you. All the windows are dark, too. There is a central road around which all the houses seem to have been built.
  Or rather, probably, the road was made to connect the first houses and then the others were built along it.>

  <narrator>: my house is the one on the edge of the road. Since my house was one of the early ones, it was built on the current outskirts of the village and
  i never really had any reason to move. The road was made a long time after it was built, connecting my house and the house of a certain friend of mine first,
  and then extending into the village.

  <You come to the house <narrator> was talking about. The door is not locked, the <narrator> just open is>

  <narrator>: We didn't really need any locks on the doors, at least here in the village, not like there was anything to steal that the people couldn't easily make
  for you if you asked nicely.

  <The <narrator> finds the light switch on the left and turns the lights on.> << The text background changes to reflect the lights? >>

  <narrator>: Surprisingly, the light still works, too. And don't ask how we got electricity here, i don't quite understand it myself.

  Yeah, alright, i really had no intention to anyway. Maybe i'll ask someone else who might know, if there ever comes someone
  else besides the two of us.

  Sure, I knew some people who could explain it, but I don't know if we'll ever be able to see them, or if anyone comes back at all.
  Anyway. I'm really tired from all this walking, spending your time in an empty room for so long doesn't motivate one to move much.
  So.. there's only one bed and we'll have to share it, since i never bothered with a second one, nobody stayed for the night here, probably because everyone lived so close together.
  You can check out the rest of the house if you want, since you'll probably be spending some time here.

  Check out the..
  - Living room :: You check out the living room. It's decently sized and has a sofa in it. On the opposite side of the room there are several bookshelves
                   packed with various books. Some of the names that stand out are "The history of everything" and "How the world works, as explained by its creator".
                   On the other side of the shelf, there are several books that seem to be about the different philosophical traditions of this world. There's also
                   something resembling a computer on the table nearby, but you decide not to touch it for now. The window in the room faces the other house that stands nearby.
                   There's not much else in this room.
                   # Set want to talk about the computers
  - Kitchen :: The kitchen is not very big, there are a few cupboards that have dishes in the, other have some of the plants you've seen earlier, but dried.
               Most of the food on the kitchen seems to be plant-based, except in the fridge there's something that looks like milk, but you decide not to taste it,
               since it's not your house. Maybe you should inquire the <narrator> about the food in this world later. Other than all the storage places on the kitchen,
               there's a table with a few chairs and a window that faces the forest you just came from.
               # Set want to talk about plant based food
  - Bathroom :: On the left, there's a moderately sized bathtub, near which there's a small shelf with some kind of soap looking thing and a washcloth.
                On the right, a small sink stands, with its own bar of soap. There's also a very small window near the ceiling, you can only see the dark sky through it.
                Unlike in the room you just came from, the bathroom's floor and walls are made of stone-looking tiles, not wood. You decide to check if the sink works,
                and sure enough it does. At first the water is very cold, but you figure out the turning the knob on the faucet makes it warm or even hot. You wash your hands
                using the soap bar, it feels pretty nice.
  - Go the bed (=>)

  You go to the bedroom, it's not too big, there are two cupboards on both sides of the bed.

  - IF explored at least one room :: The <narrator> is already asleep.  You say "good night" to yourself, although you're not sure what will happen
                                     when you fall asleep, since you don't seem to belong to this world, unlike the <narrator> who is fast asleep already.
  - ELSE ::  Sure, yeah, i'm getting tired too. Although i'm not sure what happens when i'll go to bed, since it seems like i'm not exactly here like you are.

            I suppose we'll just have to see for ourselves.

            <You both lie down.>

            <narrator>: Good night.

            You too.

  <The screen goes black>

* After the first night
  After the screen goes black, the player is back in the dark room they were in and can explore a little more.
  There's a new doorway that appeared and that the player can go through. It is as badly lit as the room and has a
  simple puzzle with three switches that need to be pressed in a certain order or something similiar (TBD). After that
  a sound is heard and the player goes back to the computer. It's now the next day.
* Day 2
*** Morning
    <It seems like it's already morning and the <narrator> is already out somewhere. After a bit of searching you find them
    in the kitchen having breakfast>.

    <narrator>: Hey. Mornin'.

    Yeah.. Morning

    Slept well?

    Not really. When i "went to sleep" the screen went black and i was unable to do anything. So i figured i'll
    go look around again. Unsurprisingly, there was a new place to look at. Nothing too interesting though, a very basic
    puzzle, if you can even call it that. I wonder why it was there. But when i activated it, something happened, i guess?
    There was some kind of sound. And then i went back to the computer and it was already morning.

    Interesting.. As for me, i slept in an actual bed this time, haven't done that in a while.

    No bed here in the room i'm in. It's quite empty actually.

    Could you elaborate?

    Not much to say. It's just me and a table with the computer. Well, there's this new hallway, but it's pretty
    empty too. There really isn't anything of interest here besides the computer. Which is also the only source of light here, it seems.
    Otherwise it's dark as hell.

    Scary.

    I dunno.. Didn't really think about that until now. Well, at least for now, i'm pretty sure there's nobody else here,
    there's simply no place to hide in the two empty rooms, and the screen of this computer is taking care of darkness around too.
    It's not that bright, but it's something. Let's see if i can find something to brighten this place up in the future.

    Yeah, even if you aren't afraid, sitting in the darkness doesn't do you any good.

    Anyway, what is this you're having for breakfast?

    <The <narrator> seems to have something that looks like cereal with milk in the bowl>

    The liquid in the bowl is a juice of a plant that grows in a region far from here. The region and the plant were discovered in an expedition
    to a place outside the known land of that time. When they were there, they discovered a different biome, a colder one. They told that it was
    a bit more chilly out there and that the plants and trees there were different. They took some samples back, then the local
    people discovered various applications for them. One of which was to use them as food, because of their taste. You see, we don't really
    need food to survive. We don't feel hunger. But we do feel the taste, and that is what food is used here for. To satisfy one's curiosity in new tastes and
    to feel good after an interesting meal. Wanna check the juice out?

    <The narrator passes you a carton, presumably full of juice>

    Yeah, i'm curious how it tastes now.

    <You take a sip. It tastes like milk with a slight bit of grass>

    <p>: This taste reminds me of a certain drink i know about for some reason. This seems to be a reoccuring pattern, too..
    I know about something, but i can't remember where i got that knowledge from.

    That's.. unusual. I felt like this too, but when the "creator" came and told us how this world came to be, it became ovious.

    Well, that doesn't really work in my case, since i'm here and you're there, does it?

    Indeed. You'll have to figure it out in some other way.

    So.. What about the other part of your meal?

    Oh, it's the leaves of a bush growing around, people have been using it as food for a long time. When dried, it changes its taste,
    and some people like it more in that state. I do, for example. Do you wish to taste this too?

    Since we're on it, yeah i'll take a bite.

    <You take a few from the box and taste them. It's really just dried leaves>

    Uh i dunno about this one. Really, it tastes like leaves.

    That's because they are leaves?

    Yeah. I just thought it'd be something more surprising.

    Sorry to disappoint! I like it, though. Now, let me finish my breakfast and we'll go take a stroll outside.

    Sure, take you time.

    <You spend a few minutes in the kitchen while the <narrator> finishes their breakfast>

    <narrator>: Well, i'm done.. Let's go.

    <You go outside. The <narrator> turns the lights off as they close the door. They then look somewhere behind you with a confused look>.

    <narrator>: Ah. This wasn't here yesterday. Might be the result of you solving that "puzzle" you talked about yesterday.

    <You turn around and see that in the distance, there are now tall buildings>

    <p> So this is the city you talked about yesterday?

    It seems like that's the one. Indeed.

    So, now we'll go check it out, right?

    If you insist. It's going to be a long walk though.

    It's not like we're short on time.. If i were to describe how much time we have, i'd say we've got all of it. Besides,
    not like there's anything else to do. Boredom really is a big problem around here..

    Oh yes, it very much is. So, there was a stone pathway that lead from here to the city. It was layed a bit
    after the city was started, before the tall buildings were there to help people find where the city was.
    Let's see if we can find it..

    <After a short walk you find the stone road on the other side of the village>

    <narrator>: Here it is. Let's go here, then. It's far more comfortable to walk on the road instead of going through the bushes and grass.

    Yeah. Getting through that forest yesterday was no fun. Well, the getting throught the forest part was no fun, but listening
    you talk about the world was alright. So i guess i'll get to have more of that but without the no fun part.
*** The long walk questions
    Sure. What do you want to talk about?

     # If the food is good
     # Where you are staying the night
     # The weather (?)
     # The sights to see
**** IF (want to talk about the computers) THEN the computers here, what are they like and how do they work?
     So.. You have computers here? How do they actually work?

     Yes! I actually have one, too. You might've seen it in my living room. I got it recenly, if you don't count all the time i've spent alone in that empty room alone.
     I used to have a big one, until it eventually broke down, just refused to boot.. So i got a new one. Couldn't really get the same one, since they didn't make them like that anymore.
     So i got a new shiny slick one. It was faster, but i really don't use it much. I'm not very good with computers, you see. Checking mail, reading
     people's blogs and writing in my own blog was good enough for me. We had a network that connected all computers together, but once again,
     i have no idea how it works, so you'll have to ask someone else about that, provided we ever find anyone else..

     You have a blog? What is it about?

     Oh all the things. It's more like a micro-blog, you know? Where you put all the things that are happening to you right now. And check what other people
     are doing. It's pretty fun. That way it's easier to keep up with your friends even when they move. I was really happy when i was told about it, and that
     people i wanted to keep talking with were on there. So i started using it a lot. Of course, now that everyone's gone, there is probably nobody on there..
     We could still check it later when we get back. Or maybe we could find some kind of computer cafe in the city.

     Yeah, for sure. I wanna see it.

**** IF (want to talk about plant based food) THEN What's with the food here, it's all made from plants?
     <p>: It seems like all the food is made out of various plants. Do all people here only eat that?

     Yes? Well, we wouldn't eat each other, would we?

     Fair.. Here we have other foods, which are made of various creatures that are deemed not self-aware. People would raise them specifically to
     cook them later. I can't remember why i do, but i know that it exists and how it happens..

     That sounds pretty awful.

     It does, kind of. But these creatures live their best lives before they are made into food. They're well fed and cleaned. I can't say i'm too much against that,
     especially if they really don't even recognize themselves, just follow the instincts.

     While i can understand that, we never really sank that low as to abuse the less aware creatures.

     Yeah, i guess some of the reasoning for that would be that people in your world don't actually need to eat to survive. Eating other creatures gives one way more
     nutrients. Maybe that was the main reason people eat them: to survive the tougher times. I'm sure there are people out there that still only eat plant-based foods like you here do.

     Requiring food to survive indeed makes it a lot more difficult, it does make sense that people would use any means necessary to survive of course.
     Still, i'm glad that for us this problem never existed and we could circumvent it entirely and don't have a dire need to abuse creatures to survive and it makes
     me feel unwell that this had to happen in your case.

     Again, surely there must be other people that feel like you out there. Although i bet the opposite is also true, there might be people that enjoy it.

     What an awful world that must be. Still, surely, not all hope is lost if someone understand that it's bad.

     I suppose that's just how it is. The world is cruel like that sometimes.

**** Do people always look the same since they don't age?
     <p>: So.. if people here don't age, does that mean their appearance doesn't change since when they first find themselves here?

     Pretty much. Since i woke up here my appearance didn't change at all. The hair and the nails still grow, but that's practically it.
     So i still have to look after them, but except that.. not much changes. You can get new clothes to change your looks
     a bit, certainly, but other than that the looks don't change too much. Some people actually wondered if anything could be done
     about that, but the research was started relatively late and didn't go that far.

     I see.. So after people wake up here, they are all already aged and that never changes. Were all people here grown-ups?

     Not all of them, no. The "age" ranged considerably, there were all kinds of people. You couldn't really judge anyone by their appearance, because someone
     could look like a child, but have lived a long life already. Perhaps, we could talk to the people who did research on the topic, provided we'd find someone like that.
     Maybe in the city, since most of them lived there, it was the place for researchers to gather.
**** What's the city like in general?
     <p>: What's the city we're heading to like in general?

     Uhm.. It's big! And it had a lot of people doing many things. A lot bigger than the village, you know.
     The buildings there were also actually placed in places specifically designated for them, unlike in our village,
     where things were just made up as the time progressed and then were connected with a road. For the city,
     they've actually made a plan.. And uhm.. the building there are tall and they house many people on many floors.
     And since it's that big there are also means of easier transportation between the parts of the city. Although they
     wouldn't help us since they require someone to operate them and I sure as hell have no idea how to do it. We can probably
     see some of them though, or at least i hope we can.

     Interesting.. so, it's big, that's not really new.. What about nighttime, how's it at night?

     It'd be all lit up if there were people, night life there is a normal thing there, unlike in the village where we mostly go to bed and get up early; in the city,
     many people are more active at night, just because of the way they made their schedule; there are entertainment places where they go to meet their friends and make new ones,
     have a drink, dance. I tried that lifestyle for some time when i was in the city but i really just couldn't handle it, i think it takes a lot of time to get used to it; getting up
     so late just feels wrong.. and staying up after midnight is just too tiring for me..
**** Is the food in the city any different?
     <p>: Since the city is so big, they probably have some interesting different cuisine, right?

     Precicely so. The food there is made of things delivered there from different places. Since they don't have
     much of their own food growing, they have to import it from all the places around the world, while the rest of the world
     gets the "techonolgy" pieces from them, like computers, and phones. As a consequence, you can also get food from other parts of the world there for
     yourself if you go to the city. The juice you saw this morning, for example, i got from my last trip to the city. I try all kinds of food there and those i like i
     take back with me to enjoy at home.

     # Set want to talk about plant based food AND want to talk about the computers
