prefab = "look_closer_image"

[drawable]
texture_asset = "look_up_bg"

[children.fan.drawable]
kind = "sprite"
texture_asset = "look_up_fan"
z = 1
layer = "overlay"

[children.fan.transformable]
position = [309, 247]
origin = [309, 247]
rotation = 30

[children.fan.rotation]
rotation_speed = 0.3

[children.caption.drawable]
text = { text = "The night sky.. it's far away.." }