[shaders.cave]
lightPoint = { module = "components.tilemap", name = "player_light_position"}
n = 1

[entities.tilemap.tilemap]
tiles = '''
##########----
ep        #---
#######   #---
------#   #---
------#   #---
-######   #---
#         #---
#         #---
n         #---
#         #---
#         #---
-#########----
--------------
--------------
'''
texture = "cave_tilemap"
sheet = "resources/sprites/room/cave_tileset/"

[entities.tilemap.tilemap.map."#"]
sprites = ["Brickwork"]
type = "wall"

[entities.tilemap.tilemap.map."-"]
sprites = ["Wall"]
type = "wall"

[entities.tilemap.tilemap.map." "]
sprites = ["Floor"]
type = "floor"

[entities.tilemap.tilemap.map."p"]
# The floor underneath
sprites = ["Floor"]
# The player sprite
player_sprite = "Player"
type = "player"

[entities.tilemap.tilemap.map."e"]
# Entrance
sprites = ["Floor"]
type = "wall"

[entities.tilemap.tilemap.map."n"]
sprites = ["Brickwork", "Note"]
type = "interaction"
callback = { module = "components.note", name = "read_note", args = [ "cave-1" ] }

# Text for talking
[entities.talk_text]
tags = [ "TileTalkText" ]

[entities.talk_text.drawable]
kind = "text"
text = { text = "", font_size = 24 }
z = 0
layer = "overlay"
enabled = false

[entities.talk_text.transformable]
position = [100, 800]

[entities.interaction_text]
tags = [ "InteractionText" ]

[entities.interaction_text.drawable]
kind = "text"
text = { text = "", font_size = 32 }
layer = "overlay"
z = 0
enabled = false

[entities.interaction_text.transformable]
position = [100, 900]