[shaders.room_darker]
n = 1
ambientLightLevel = 0.4

[shaders.circle_light]
n = 2
point = [877, 656]
brightness = 0.1

[entities.background.drawable]
kind = "sprite"
texture_asset = "status_room"
z = 0

[entities.player]
prefab = "player"

[entities.player.transformable]
position = [300, 811]

[entities.passage]
prefab = "passage"
transformable = { position = [ 300, 723 ] }

[entities.passage.passage]
from = "status_room"
to = "walkway_room"
player_y = 644

[entities.left_wall]
transformable = { position = [95, 500] }
collider = { mode = "constant", size = [10, 400] }

[entities.right_wall]
transformable = { position = [960, 500] }
collider = { mode = "constant", size = [10, 400] }

[entities.computer]
transformable = { position = [850, 600] }
collider = { mode = "constant", size = [80, 100], trigger = true }

[entities.computer.interaction]
callback = { module = "components.look_closer", name = "look", args = { prefab = "status_room/computer" } }
action_text = "look at the screen"

[entities.ladder.transformable]
position = [ 418, 568 ]

[entities.ladder.collider]
size = [ 100, 200 ]
mode = "constant"
trigger = true

[entities.ladder.passage]
from = "status_room"
to = "food_room"
player_y = 644

[entities.ladder.interaction]
action_text = "climb down"
callback = { module = "components.passage", name = "switch_room", self = true }

[entities.ladder_up.transformable]
position = [ 418, 568 ]

[entities.ladder_up.collider]
size = [ 100, 200 ]
mode = "constant"
trigger = true

[entities.ladder_up.interaction]
action_text = "climb up"
callback = { module = "components.status_room", name = "check_way_up", args = [ "Seems like the way up is blocked by something" ] }

[entities.box_note.transformable]
position = [ 851, 672 ]

[entities.box_note.collider]
size = [ 50, 50 ]
trigger = true
mode = "constant"

[entities.box_note.interaction]
callback = { args = [ "no_crafting_iteration" ], module = "components.note", name = "read_note" }
action_text = "read the note"