[shaders.room_darker]
n = 1
ambientLightLevel = 0.4

[entities.background.drawable]
kind = "sprite"
texture_asset = "first_puzzle_room"
z = 0

[entities.background_wall_overlay.drawable]
kind = "sprite"
texture_asset = "first_puzzle_room_wall_overlay"
z = 1

[entities.player]
prefab = "player"

[entities.player.transformable]
position = [159, 820]

[entities.left_wall]
transformable = { position = [70, 500] }
collider = { mode = "constant", size = [10, 400] }

[entities.right_wall]
transformable = { position = [650, 500] }
collider = { mode = "constant", size = [10, 400] }

[entities.first_button]
prefab = "first_puzzle_button"
transformable = { position = [ 300, 650 ] }
interaction = { callback = { args = [ "first" ] } }
first_puzzle_button = { n = "first" }

[entities.second_button]
prefab = "first_puzzle_button"
transformable = { position = [ 400, 650 ] }
interaction = { callback = { args = [ "second" ] } }
first_puzzle_button = { n = "second" }

[entities.third_button]
prefab = "first_puzzle_button"
transformable = { position = [ 500, 650 ] }
interaction = { callback = { args = [ "third" ] } }
first_puzzle_button = { n = "third" }

[entities.puzzle_jingle_player]
sound_player = { sound_asset = "puzzle_jingle", activatable_callback = { module = "components.first_puzzle", name = "first_puzzle_solved_music" } }

[entities.passage]
prefab = "passage"
transformable = { position = [120, 750], scale = [1, 1] }

[entities.passage.passage]
from = "first_puzzle_room"
to = "computer_room"
player_y = 644
