[shaders.room_darker]
n = 1
ambientLightLevel = 0.4

[entities.background.drawable]
kind = "sprite"
texture_asset = "first_puzzle_room"
z = 0

[entities.player]
prefab = "player"

[entities.player.transformable]
position = [159, 820]

[entities.left_wall]
transformable = { position = [70, 500] }
collider = { mode = "constant", size = [10, 400] }

[entities.right_wall]
transformable = { position = [650, 500] }
collider = { mode = "constant", size = [10, 400] }

[entities.first_button]
prefab = "first_puzzle_button"
transformable = { position = [ 300, 650 ] }
interaction = { args = [ "first" ] }
first_puzzle_button = { n = "first" }

[entities.second_button]
prefab = "first_puzzle_button"
transformable = { position = [ 400, 650 ] }
interaction = { args = [ "second" ] }
first_puzzle_button = { n = "second" }

[entities.third_button]
prefab = "first_puzzle_button"
transformable = { position = [ 500, 650 ] }
interaction = { args = [ "third" ] }
first_puzzle_button = { n = "third" }

[entities.puzzle_jingle_player]
sound_player = { sound_asset = "puzzle_jingle", activate_callback_name = "first_puzzle_solved" }

[entities.passage]
prefab = "passage"
transformable = { position = [120, 750], scale = [1, 1] }
interaction = { args = { room = "day2/computer_room", player_pos = [900, 644] } }

[entities.interaction_text]
prefab = "interaction_text"