[drawable]
kind = "sprite"
texture_asset = "button"
z = 1

[animation]
sheet = "resources/sprites/room/button/"
playing = false
playable = false

[interaction]
initial_state = "wrong"
state_map = { right = 2, wrong = 1 }
interaction_sound_asset = "button_press"
callback = { module = "components.first_puzzle", name = "button_callback" }
activatable_callback = { not = { module = "components.first_puzzle", name = "first_puzzle_solved" } }
action_text = "press the button"

[collider]
mode = "sprite"
trigger = true