[drawable]
kind = "sprite"
texture_asset = "passage"
z = 1

[transformable]
origin = [0, 184]
scale = [-1, 1]

[interaction]
callback = { module = "components.passage", name = "switch_room", self = true }
action_text = "go through"

[collider]
mode = "sprite"
trigger = true