[assets.sprites]
mainchar = "resources/sprites/mainchar/mainchar.png"

[assets.sounds]
footstep = "resources/sounds/footstep.ogg"

[drawable_sprite]
sprite_asset = "mainchar"
z = 2
origin = [44, 176]

[animation]
sheet = "resources/sprites/mainchar/"

[player_movement]
footstep_sound_asset = "footstep"