[drawable]
kind = "sprite"
texture_asset = "mainchar"
z = 3

[transformable]
origin = [44, 176]

[animation]
sheet = "resources/sprites/mainchar/"

[player_movement]
footstep_sound_asset = "footstep"

[collider]
mode = "sprite"