[drawable]
kind = "sprite"
texture_asset = "mainchar"
z = 3

[transformable]
origin = [44, 176]

[animation]
sheet = "resources/sprites/mainchar/"

[player_movement]
footstep_sound_asset = "footstep"

[collider]
mode = "sprite"

[children.interaction_text]
tags = [ "InteractionText" ]

[children.interaction_text.drawable]
kind = "text"
text = { text = "[E] to", font_size = 24 }
z = 2
enabled = false

[children.interaction_text.transformable]
position = [-50, 0]